from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(310, 40, 231, 16))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.selectFolder = QtWidgets.QPushButton(self.centralwidget)
        self.selectFolder.setGeometry(QtCore.QRect(330, 100, 191, 32))
        self.selectFolder.setObjectName("selectFolder")
        self.kernelLine = QtWidgets.QLineEdit(self.centralwidget)
        self.kernelLine.setGeometry(QtCore.QRect(310, 160, 231, 21))
        self.kernelLine.setText("")
        self.kernelLine.setAlignment(QtCore.Qt.AlignCenter)
        self.kernelLine.setObjectName("kernelLine")
        self.ejecutarButton = QtWidgets.QPushButton(self.centralwidget)
        self.ejecutarButton.setGeometry(QtCore.QRect(370, 220, 113, 32))
        self.ejecutarButton.setObjectName("ejecutarButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(260, 290, 371, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.folderILine = QtWidgets.QLineEdit(self.centralwidget)
        self.folderILine.setGeometry(QtCore.QRect(310, 70, 231, 21))
        self.folderILine.setAlignment(QtCore.Qt.AlignCenter)
        self.folderILine.setObjectName("folderILine")
        self.showResultFolder = QtWidgets.QPushButton(self.centralwidget)
        self.showResultFolder.setGeometry(QtCore.QRect(330, 360, 201, 32))
        self.showResultFolder.setObjectName("showResultFolder")
        self.folderDLine = QtWidgets.QLineEdit(self.centralwidget)
        self.folderDLine.setGeometry(QtCore.QRect(320, 330, 221, 21))
        self.folderDLine.setObjectName("folderDLine")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(760, 410, 20, 121))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(650, 290, 131, 20))
        self.label.setText("")
        self.label.setObjectName("label")
        self.messageLabel = QtWidgets.QLabel(self.centralwidget)
        self.messageLabel.setGeometry(QtCore.QRect(400, 260, 60, 16))
        self.messageLabel.setText("")
        self.messageLabel.setObjectName("messageLabel")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 390, 781, 151))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 779, 149))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.infoText = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.infoText.setGeometry(QtCore.QRect(0, 0, 761, 141))
        self.infoText.setObjectName("infoText")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuVanessa = QtWidgets.QMenu(self.menubar)
        self.menuVanessa.setObjectName("menuVanessa")
        self.menuJacqueline = QtWidgets.QMenu(self.menubar)
        self.menuJacqueline.setObjectName("menuJacqueline")
        self.menuAugusto = QtWidgets.QMenu(self.menubar)
        self.menuAugusto.setObjectName("menuAugusto")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuVanessa.menuAction())
        self.menubar.addAction(self.menuJacqueline.menuAction())
        self.menubar.addAction(self.menuAugusto.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Procesador de imágenes en paralelo"))
        self.selectFolder.setText(_translate("MainWindow", "Seleccionar folder"))
        self.kernelLine.setPlaceholderText(_translate("MainWindow", "Tamaño de kernel (55-150)"))
        self.ejecutarButton.setText(_translate("MainWindow", "Ejecutar"))
        self.showResultFolder.setText(_translate("MainWindow", "Ir a carpeta de resultados"))
        self.menuVanessa.setTitle(_translate("MainWindow", "Vanessa"))
        self.menuJacqueline.setTitle(_translate("MainWindow", "Jacqueline"))
        self.menuAugusto.setTitle(_translate("MainWindow", "Augusto"))
